server.port=8080

spring.datasource.url=jdbc:postgresql://ewallet-postgres.postgres.database.azure.com:5432/ewalletdb?sslmode=require
spring.datasource.username=suriya@ewallet-postgres
spring.datasource.password=Worldt20!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis (keep if needed)
spring.redis.host=redis-10685.c301.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port=10685
spring.redis.password=VrFmfFYRL6JRrfkSugswi3xRvAREZI7t
spring.redis.ssl=true