server.port=9090

spring.datasource.url=jdbc:postgresql://ewallet-postgres.postgres.database.azure.com:5432/ewalletdb
spring.datasource.username=suriya@ewallet-postgres
spring.datasource.password=Worldt20!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect